.*: Assembler messages:
.*: Error: illegal operands `c\.lbu x0,0\(x9\)'
.*: Error: illegal operands `c\.lbu x8,0\(x2\)'
.*: Error: illegal operands `c\.lhu x8,1\(x9\)'
.*: Error: illegal operands `c\.lhu x8,64\(x9\)'
.*: Error: illegal operands `c\.lbusp x7,0\(sp\)'
.*: Error: illegal operands `c\.lbusp x8,16\(sp\)'
.*: Error: illegal operands `c\.lhusp x8,1\(sp\)'
.*: Error: illegal operands `c\.shsp x8,32\(sp\)'
